export const GET_ORDERS_COUNT = 'GET_ORDERS_COUNT'
export const GET_ORDERS = 'GET_ORDERS'
export const LOAD_PRODUCTS_BY_ID = 'LOAD_PRODUCTS_BY_ID'


export const GET_PRODUCTS_COUNT = 'GET_PRODUCTS_COUNT'
export const GET_TYPES = 'GET_TYPES'
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS'
export const GET_PRODUCT_ORDER = 'GET_PRODUCT_ORDER'